# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f648f570342ff359c4cf984fd528afc6deafef9e2e3f797eed15ac9c2349ffd30617ed7c4745bd119029dbaf969e30f6d15b0043b7b575fa5243d46301888669

test:
  secret_key_base: 4a71b08f1a60ec7438279d0a67e2e478cc4ca2a8667243239b38be8058cc026d88f2b0e1afdc2f30b87609ed4336e104cb6e364381195cc9a090c60765e9cc70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
